trigger:
- main

variables:
 test: 'Raj'

pool:
 vmImage: 'ubantu-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: new
      steps:
      - script: |
         echo "Abhi-$(test)"