trigger:
- main

name: MyPipeline

stages:
- stage: Build
  displayName: Build
  pool :
   vmImage: 'ubuntu-latest'
  variables: 
    test: Raj
  jobs:
    - job: new
      steps:
      - script: |
         echo "Abhi-$(test)"
- stage: Test
  displayName: test
  dependsOn: Build
  isSkippable: false
  variables:
    test: AAABBH
  jobs:
    - job: tee
      steps:
      - script: |
          echo "$(test)"
    - job: job 
      steps:
      - script: |
          echo "testb"
  pool:
    vmImage: 'windows-latest'
  
