trigger:
- main

variables:
 test: 'Raj'

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: new
      steps:
      - script: |
         echo "Abhi-$(test)"
  pool:
    vmImage: 'ubuntu-latest'
- stage: Test
  displayName: test
  dependsOn: Build
  isSkippable: false
  
  jobs:
    - job: tee
      steps:
      - script: |
          echo "Test"
    - job: job 
      steps:
      - script: |
          echo "testb"
  pool:
    vmImage: 'ubuntu-latest'
  
