trigger:
- main

name: MyPipeline

stages:

- stage: Build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  variables: 
    test: Raj
  jobs:
    - job: new
      steps:
        - script: |
            echo "Abhi-$(test)-$(dbname)"

- stage: Test
  displayName: test
  dependsOn: Build
  isSkippable: false
  variables:
    test: AAABBH
  jobs:
    - deployment: testDeployment
      environment: test-approval-env
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  echo "$(test)"
              - script: |
                  echo "testb"
  pool:
    vmImage: 'windows-latest'
